name: testing actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script and print event payload that triggered it
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        ls /
        cat /workflow/event.json
